version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    groups:
      development-tools:
        patterns: ["build", "mypy", "pip-audit", "pytest", "pytest-cov", "ruff", "types-*"]
